#!/usr/bin/env python
import os
import shutil
import subprocess

from SCons.Script import SConscript, ARGUMENTS, Action, Copy

MACOS = "macos"
LINUX = "linux"
WINDOWS = "windows"
IOS = "ios"
ANDROID = "android"
WEB = "web"

# target_path = ARGUMENTS.pop("target_path", "./bin/")
# target_name = ARGUMENTS.pop("target_name", "libGodotFmod")
fmod_lib_dir = ARGUMENTS.pop("fmod_lib_dir", "libs/fmod/")

# Although FMOD's WebAssembly libraries are built with pthreads / shared memory support, Godot doesn't yet like it.
# For web builds, default to single-threaded godot-cpp (unless the user explicitly overrides it).
platform_arg = ARGUMENTS.get("platform")

# if platform_arg == WEB and "threads" not in ARGUMENTS:
#     ARGUMENTS["threads"] = "no"

Import('env')
Import("env_modules")

#env = env.Clone()

# "template_debug"/"template_release"/"editor"
compile_target = env["target"]

architecture = env["arch"]

source_paths = []

include_paths = []

lib_paths = []

libs = []

link_flags = []

cc_flags = []

# # Add those directory manually, so we can skip the godot_cpp directory when including headers in C++ files
# godot_cpp_source_path = [
#     os.path.join("godot-cpp", "include","godot_cpp"),
#     os.path.join("godot-cpp", "gen", "include","godot_cpp")
# ]

# source_paths.extend([env.Dir(d) for d in godot_cpp_source_path])

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
source_glob_paths = [
    '*.cpp',
    'src/*.cpp',
    'src/callback/*.cpp',
    'src/core/*.cpp',
    'src/data/*.cpp',
    'src/tools/*.cpp',
    'src/helpers/*.cpp',
    'src/nodes/*.cpp',
    'src/resources/*.cpp',
    'src/studio/*.cpp',
    'src/plugins/*.cpp',
]

[source_paths.extend(Glob(path, strings=True)) for path in source_glob_paths]

print(source_paths)

lfix = ""

debug = False

if compile_target == "template_debug" or compile_target == "editor":
    lfix = "L"
    debug = True


studio_inc_dir = "/studio/inc/"
core_inc_dir = "/core/inc/"
studio_lib_dir = "/studio/lib/"
core_lib_dir = "/core/lib/"

platform_dir = platform_arg if platform_arg != MACOS else "osx"

arch_info_table = {}

if platform_arg == WINDOWS:
    arch_info_table = {
        "x86_64" : "x64",
        "x86_32" : "x86",
    }
elif platform_arg == LINUX:
    arch_info_table = {
        "x86_64": "x86_64",
        "x86_32": "x86_32",
        "arm64": "arm64",
        "rv64": "rv64",
    }
elif platform_arg == ANDROID:
    arch_info_table = {
        "armv7": "armeabi-v7a",
        "arm64": "arm64-v8a",
        "x86": "x86",
        "x86_64": "x86_64"
    }


arch_dir = ""

if architecture in arch_info_table:
    arch_dir = arch_info_table[architecture] + "/"
elif platform_arg == WEB:
    arch_dir = "w32/"

include_paths.extend([fmod_lib_dir + platform_dir + core_inc_dir, fmod_lib_dir + platform_dir + studio_inc_dir])
    
lib_paths.extend([fmod_lib_dir + platform_dir + core_lib_dir + arch_dir, fmod_lib_dir + platform_dir + studio_lib_dir + arch_dir])

lib_prefix = "lib" if platform_arg != WEB and platform_arg != WINDOWS else ""

lib_suffixes = {
    MACOS: ".dylib",
    LINUX: ".so",
    WINDOWS:"_vc.lib",
    IOS: "_iphoneos.a",
    ANDROID: ".so",
    WEB: "_wasm.a",
}

core_lib = lib_prefix + "fmod" + lfix + lib_suffixes[platform_arg]

studio_lib = lib_prefix + "fmodstudio" + lfix + lib_suffixes[platform_arg]

# if platform_arg == WEB:
#     link_flags.extend([core_lib, studio_lib])
# else:
libs.extend([File(fmod_lib_dir + platform_dir + core_lib_dir + arch_dir + core_lib), File(fmod_lib_dir + platform_dir + studio_lib_dir + arch_dir + studio_lib)])


if platform_arg == MACOS:
    link_flags.extend(
        [
            "-framework",
            "Cocoa",
            "-Wl,-undefined,dynamic_lookup",
            "-rpath", "@loader_path/.."
        ]
    )

elif platform_arg == LINUX:
    cc_flags.extend(["-fPIC", "-Wwrite-strings"])
    
    link_flags.extend(["-Wl,-R,'$$ORIGIN'", "-m64", "-fuse-ld=gold"])

elif platform_arg == WINDOWS:
    link_flags.extend(["/WX"])
    
    if debug:
        cc_flags.extend(["/FS", "/Zi"])

elif platform_arg == IOS:
    link_flags.extend([
        '-Wl,-undefined,dynamic_lookup', "-miphoneos-version-min=" + env["ios_min_version"]
    ])

elif platform_arg == WEB:
    link_flags.extend(["-sEXPORTED_RUNTIME_METHODS=ccall,cwrap,setValue,getValue"])

env_module = env


env_module = env.Clone()
env_module.add_source_files(env.modules_sources, source_paths)
env_module.Append(CPPPATH=include_paths)
env_module.Append(CPPPATH="src/")
env_module.Append(CPPPATH="./")
# env.Append(LINKFLAGS=link_flags)

env.Append(LIBPATH=lib_paths)
env.Append(LIBS=libs)
# env.Append(CCFLAGS=cc_flags)


# #Output is placed in the addons directory of the demo project directly
# target = "{}{}/{}.{}.{}".format(
#     target_path, platform_arg, target_name, platform_arg, compile_target
# ) \
# if platform_arg != ANDROID \
# else "{}{}/{}/{}.{}.{}".format(
#     target_path, platform_arg, architecture, target_name, platform_arg, compile_target
# )


# if platform_arg == MACOS:
#     target = "{}.framework/{}.{}.{}".format(
#         target,
#         target_name,
#         platform_arg,
#         compile_target
#     )
# else:
#     target = "{}.{}{}".format(
#         target,
#         architecture,
#         env["SHLIBSUFFIX"]
#     )

#library = env.SharedLibrary(target=target, source=sources)


# def sys_exec(args):
#     proc = subprocess.Popen(args, stdout=subprocess.PIPE, text=True)
#     (out, err) = proc.communicate()
#     return out.rstrip("\r\n").lstrip()


# if platform_arg == IOS:
#     xcframework_path = "{}{}/{}.{}.{}.xcframework".format(
#         target_path,
#         platform_arg,
#         target_name,
#         platform_arg,
#         compile_target
#     )

#     def create_xcframework(self, arg, env, executor = None):
#         sys_exec(["xcodebuild", "-create-xcframework", "-library", target, "-output", xcframework_path])
#         sys_exec(["rm", target])
#         sys_exec(["/usr/libexec/PlistBuddy", "-c", "Add :MinimumOSVersion string " + env["ios_min_version"], "{}/Info.plist".format(xcframework_path)])

#     create_xcframework_action = Action('', create_xcframework)

#     AddPostAction(library, create_xcframework_action)


# def copy_fmod_libraries(self, arg, env, executor = None):
#     addon_fmod_libs_output = "{}{}/".format(
#         target_path, platform_arg
#     ) if platform_arg != ANDROID else "{}{}/{}/".format(
#         target_path, platform_arg, architecture
#     )

#     source_files = [env.Glob(os.path.join(source_dir, '*.*')) for source_dir in lib_paths]
    
#     [[shutil.copy(str(file), addon_fmod_libs_output) for file in files] for files in source_files]


# # web bundles everything inside the final .wasm - no need to export libs
# if platform_arg != WEB:
#     copy_fmod_libraries_action = Action('', copy_fmod_libraries)
#     AddPostAction(library, copy_fmod_libraries_action)

# Default(library)